import proxy_list from "./request/proxy_list"
import getConsecutiveItemFromList from "./utilities/getConsecutiveItemFromList"

const nextProxy = getConsecutiveItemFromList(proxy_list)

console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())

console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())
console.log(nextProxy())